#Copyright 2018 OPNFV and Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: enable dpdkstat plugin
  template:
    src: dpdkstat.conf.j2
    dest: "{{ config_file_dir }}/dpdkstat.conf"
  tags:
    # require this to be explicitly enabled
    - never
    - dpdkstat

- name: enable dpdkevents plugin
  template:
    src: dpdkevents.conf.j2
    dest: "{{ config_file_dir }}/dpdkevents.conf"
  tags:
    - never
    - dpdkevents

- name: enable dpdk_telemetry plugin
  template:
    src: dpdk_telemetry.conf.j2
    dest: "{{ config_file_dir }}/dpdk_telemetry.conf"
  tags:
    - dpdk_telemetry
