#Copyright 2018 OPNFV and Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: check if libvirtd on host
  shell: ps -ef | grep libvirtd | grep -v grep > /dev/null
  register: libvirt_result
  ignore_errors: "true"
  tags:
   - virt

- name: (virt) check if rdt  is enabled
  stat:
      path: "{{ config_file_dir }}/rdt.conf"
  register: rdt_file
  tags:
    - virt

- name: enable virt plugin
  template:
    src: virt.conf.j2
    dest: "{{ config_file_dir }}/virt.conf"
  when: libvirt_result is succeeded and rdt_file.stat.exists == False
  tags:
   - virt
