# Copyright 2021 Anuket and others
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Build stable container
  docker_image:
    name: opnfv/barometer-collectd
    build:
      path: "{{ playbook_dir }}/../barometer-collectd/"
    source: build
  tags:
    - stable

- name: Build the latest container
  docker_image:
    name: opnfv/barometer-collectd-latest
    build:
      path: "{{ playbook_dir }}/../../"
      dockerfile: "docker/barometer-collectd-latest/Dockerfile"
    source: build
  tags:
    - latest

#    - name: Build collectd-experimental
#      docker_image:
#        name: opnfv/barometer-collectd-experimental
#        build:
#          path: "{{ playbook_dir }}/../../"
#          dockerfile: "docker/barometer-collectd-experimental/Dockerfile"
#          args:
#            COLLECTD_FLAVOR: experimental
#            COLLECTD_TAG: "{{ COLLECTD_TAG | default('main') }}"
#            COLLECTD_PULL_REQUESTS: "{{ COLLECTD_PULL_REQUESTS | default() }}"
#        source: build
#      tags:
#        - experimental

- name: Build collectd-6
  docker_image:
    name: "opnfv/barometer-collectd-6{{ '-' + COLLECTD_PULL_REQUESTS if COLLECTD_PULL_REQUESTS is defined }}"
    build:
      path: "{{ playbook_dir }}/../../"
      dockerfile: "docker/barometer-collectd-experimental/Dockerfile"
      args:
        COLLECTD_FLAVOR: collectd-6
        COLLECTD_TAG: "{{ COLLECTD_TAG | default('collectd-6.0') }}"
        COLLECTD_PULL_REQUESTS: "{{ COLLECTD_PULL_REQUESTS | default(omit) }}"
    source: build
  tags:
    - collectd-6

- name: Build test_app for write_http
  docker_image:
    name: test-collectd-write_http
    build:
      path: "{{ playbook_dir }}/../flask_app/"
    source: build
  tags:
    - flask_test

