# Copyright 2018-21 Anuket, Intel Corporation and others
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: remove bar-collectd container
  docker_container:
    name: bar-collectd
    state: absent
  tags:
    - rm_containers
    - rm_collectd_cont
  when: rm_containers|default(false)|bool == true

- name: Remove bar-collectd image
  docker_image:
    name: "{{ collectd_image_name }}"
    state: absent
  tags:
    - rm_images
    - rm_collectd_image
  when: rm_images|default(false)|bool == true

- name: check if /sys/fs/resctrl exist
  stat:
    path: /sys/fs/resctrl
  register: resctrl_dir

- name: set list of volumes to bind
  set_fact:
    volumes_list:

       - /opt/collectd/etc/:/opt/collectd/etc/
       - /var/run:/var/run
       - /tmp:/tmp
       - /var/lib/collectd:/var/lib/collectd

- name: add resctrl to container volumes
  set_fact:
    volumes_list: "{{ volumes_list + [ '/sys/fs/resctrl:/sys/fs/resctrl' ] }}"
  when: resctrl_dir.stat.exists

- name: launch collectd container
  docker_container:
    name: bar-collectd
    image: "{{ collectd_image_name }}"
    volumes: "{{ volumes_list }}"
    entry_point: "/run_collectd.sh"
    detach: yes
    state: started
    restart: yes
    privileged: yes
    network_mode: host
